# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c55a2a9a3f6444d835c626693703b3ba79815500300d62af6acf866aa16b1633fc1bf54b1853af1c688fd1923d2f69ae4ec1c24746986784a537bed7f99c3e4

test:
  secret_key_base: d72c98295e01fccf220ab7d6e3f5dbb272bef933eeda49004bb1d1141a1e9c1aa61c764bb03c3d6324decbb1803f857210d3724c3b4d38c85d72498a079fd3c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
